var dataset = new recline.Model.Dataset({
    records: [
        {state:'Alabama', abbr: 'Ala.', postalcode: 'AL', value: 869},
        {state:'Alabama', abbr: 'Ala.', postalcode: 'AL', value: 1056},
        {state:'Alaska', abbr: 'Alaska', postalcode: 'AK', value: 279},
        {state:'American Samoa', abbr: ' ', postalcode: 'AS', value: 284},
        {state:'Arizona', abbr: 'Ariz.', postalcode: 'AZ', value: 577},
        {state:'Arkansas', abbr: 'Ark.', postalcode: 'AR', value: 955},
        {state:'California', abbr: 'Calif.', postalcode: 'CA', value: 441},
        {state:'Colorado', abbr: 'Colo.', postalcode: 'CO', value: 551},
        {state:'Connecticut', abbr: 'Conn.', postalcode: 'CT', value: 258},
        {state:'Delaware', abbr: 'Del.', postalcode: 'DE', value: 212},
        {state:'Dist. of Columbia', abbr: 'D.C.', postalcode: 'DC', value: 203},
        {state:'Florida', abbr: 'Fla.', postalcode: 'FL', value: 30},
        {state:'Georgia', abbr: 'Ga.', postalcode: 'GA', value: 609},
        {state:'Guam', abbr: 'Guam', postalcode: 'GU', value: 541},
        {state:'Hawaii', abbr: 'Hawaii', postalcode: 'HI', value: 63},
        {state:'Idaho', abbr: 'Idaho', postalcode: 'ID', value: 125},
        {state:'Illinois', abbr: 'Ill.', postalcode: 'IL', value: 410},
        {state:'Indiana', abbr: 'Ind.', postalcode: 'IN', value: 631},
        {state:'Iowa', abbr: 'Iowa', postalcode: 'IA', value: 486},
        {state:'Kansas', abbr: 'Kans.', postalcode: 'KS', value: 362},
        {state:'Kentucky', abbr: 'Ky.', postalcode: 'KY', value: 332},
        {state:'Louisiana', abbr: 'La.', postalcode: 'LA', value: 767},
        {state:'Maine', abbr: 'Maine', postalcode: 'ME', value: 199},
        {state:'Maryland', abbr: 'Md.', postalcode: 'MD', value: 571},
        {state:'Marshall Islands', abbr: ' ', postalcode: 'MH', value: 999},
        {state:'Massachusetts', abbr: 'Mass.', postalcode: 'MA', value: 205},
        {state:'Michigan', abbr: 'Mich.', postalcode: 'MI', value: 114},
        {state:'Micronesia', abbr: ' ', postalcode: 'FM', value: 63},
        {state:'Minnesota', abbr: 'Minn.', postalcode: 'MN', value: 485},
        {state:'Mississippi', abbr: 'Miss.', postalcode: 'MS', value: 581},
        {state:'Missouri', abbr: 'Mo.', postalcode: 'MO', value: 639},
        {state:'Montana', abbr: 'Mont.', postalcode: 'MT', value: 843},
        {state:'Nebraska', abbr: 'Nebr.', postalcode: 'NE', value: 449},
        {state:'Nevada', abbr: 'Nev.', postalcode: 'NV', value: 917},
        {state:'New Hampshire', abbr: 'N.H.', postalcode: 'NH', value: 127},
        {state:'New Jersey', abbr: 'N.J.', postalcode: 'NJ', value: 25},
        {state:'New Mexico', abbr: 'N.M.', postalcode: 'NM', value: 872},
        {state:'New York', abbr: 'N.Y.', postalcode: 'NY', value: 568},
        {state:'North Carolina', abbr: 'N.C.', postalcode: 'NC', value: 576},
        {state:'North Dakota', abbr: 'N.D.', postalcode: 'ND', value: 130},
        {state:'Northern Marianas', abbr: ' ', postalcode: 'MP', value: 779},
        {state:'Ohio', abbr: 'Ohio', postalcode: 'OH', value: 778},
        {state:'Oklahoma', abbr: 'Okla.', postalcode: 'OK', value: 160},
        {state:'Oregon', abbr: 'Ore.', postalcode: 'OR', value: 387},
        {state:'Palau', abbr: ' ', postalcode: 'PW', value: 319},
        {state:'Pennsylvania', abbr: 'Pa.', postalcode: 'PA', value: 222},
        {state:'Puerto Rico', abbr: 'P.R.', postalcode: 'PR', value: 512},
        {state:'Rhode Island', abbr: 'R.I.', postalcode: 'RI', value: 729},
        {state:'South Carolina', abbr: 'S.C.', postalcode: 'SC', value: 853},
        {state:'South Dakota', abbr: 'S.D.', postalcode: 'SD', value: 998},
        {state:'Tennessee', abbr: 'Tenn.', postalcode: 'TN', value: 90},
        {state:'Texas', abbr: 'Tex.', postalcode: 'TX', value: 184},
        {state:'Utah', abbr: 'Utah', postalcode: 'UT', value: 764},
        {state:'Vermont', abbr: 'Vt.', postalcode: 'VT', value: 288},
        {state:'Virginia', abbr: 'Va.', postalcode: 'VA', value: 755},
        {state:'Virgin Islands', abbr: 'V.I.', postalcode: 'VI', value: 763},
        {state:'Washington', abbr: 'Wash.', postalcode: 'WA', value: 492},
        {state:'West Virginia', abbr: 'W.Va.', postalcode: 'WV', value: 868},
        {state:'Wisconsin', abbr: 'Wis.', postalcode: 'WI', value: 825},
        {state:'Wyoming', abbr: 'Wyo.', postalcode: 'WY', value: 977}

    ],
    fields: [
        {id: 'state', type: "string"},
        {id: 'abbr', type: "string"},
        {id: 'postalcode', type: "string"} ,
        {id: 'value', type: "integer"}
    ]
});